# -*- coding: utf-8 -*-
"""Rafad LLM.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1TP2HFi06q5h4DKxKHtwRowU7vNUxC0yl
"""

from transformers import pipeline
from langchain_community.llms import HuggingFacePipeline

# إعداد الـ pipeline مع النموذج
qa_pipeline = pipeline(
    "text-generation",
    model=model,
    tokenizer=tokenizer,
    max_new_tokens=512,
    do_sample=False,  # استخدام Greedy decoding
    return_full_text=False # إضافة هذا لضمان إرجاع النص الجديد فقط
)

# لفه بـ HuggingFacePipeline
hf_llm = HuggingFacePipeline(pipeline=qa_pipeline)

from transformers import pipeline
from langchain_community.llms import HuggingFacePipeline

# إعداد الـ pipeline مع النموذج
qa_pipeline = pipeline(
    "text-generation",
    model=model,
    tokenizer=tokenizer,
    max_new_tokens=512,
    do_sample=False,  # استخدام Greedy decoding
    return_full_text=False # إضافة هذا لضمان إرجاع النص الجديد فقط
)

# لفه بـ HuggingFacePipeline
hf_llm = HuggingFacePipeline(pipeline=qa_pipeline)

!pip install langchain_community

# Commented out IPython magic to ensure Python compatibility.
# %%capture
# !pip install unsloth
# !pip uninstall unsloth -y && pip install --upgrade --no-cache-dir --no-deps git+https://github.com/unslothai/unsloth.git
# !pip install langchain faiss-cpu sentence-transformers
# !pip install transformers accelerate bitsandbytes
#

from unsloth import FastLanguageModel

model, tokenizer = FastLanguageModel.from_pretrained(
    model_name = "unsloth/mistral-7b-instruct-v0.3-bnb-4bit",  # Instruct fine-tuned model
    max_seq_length = 4096, # Increased max_seq_length to accommodate longer inputs
    dtype = None,
    load_in_4bit = True,
)

# تجهيز النموذج للتوليد
FastLanguageModel.for_inference(model)

from transformers import pipeline
from langchain_community.llms import HuggingFacePipeline

# إعداد الـ pipeline مع النموذج
qa_pipeline = pipeline(
    "text-generation",
    model=model,
    tokenizer=tokenizer,
    max_new_tokens=512,
    do_sample=False,  # استخدام Greedy decoding
    return_full_text=False # إضافة هذا لضمان إرجاع النص الجديد فقط
)

# لفه بـ HuggingFacePipeline
hf_llm = HuggingFacePipeline(pipeline=qa_pipeline)

from langchain_community.embeddings import HuggingFaceEmbeddings

# تحميل نموذج embeddings متعدد اللغات
embedding_model = HuggingFaceEmbeddings(model_name="BAAI/bge-m3")

import json
from langchain_community.vectorstores import FAISS
from langchain_text_splitters import RecursiveCharacterTextSplitter
from langchain_core.documents import Document
from langchain_community.embeddings import HuggingFaceEmbeddings
import os

# ⚠️ ملاحظة هامة: تأكد أنك تعمل ضمن بيئة Python تم تثبيت فيها المكتبات التالية:
# pip install langchain-community faiss-cpu sentence-transformers

# ✅ 1. تحديد مسار ملف JSON
# سنفترض أن ملف البيانات الذي تم إنشاؤه مسبقًا متاح هنا.
json_file_path = '/content/Absher Data.txt'

# --- نموذج التضمين المخصص للغة العربية ---
# أفضل نموذج تضمين متعدد اللغات لدعم اللغة العربية في RAG
EMBEDDING_MODEL_NAME = "intfloat/multilingual-e5-large"
print(f"✅ سيتم استخدام نموذج التضمين: {EMBEDDING_MODEL_NAME}")

# ✅ 2. تحميل البيانات من ملف JSON
try:
    with open(json_file_path, 'r', encoding='utf-8') as f:
        data = json.load(f)
    print(f"✅ تم تحميل {len(data)} سجل من ملف البيانات بنجاح.")
except FileNotFoundError:
    print(f"❌ خطأ: لم يتم العثور على الملف {json_file_path}. يرجى التأكد من وجوده في نفس المسار.")
    exit()
except Exception as e:
    print(f"❌ خطأ أثناء قراءة ملف JSON: {e}")
    exit()

# ✅ 3. تحويل البيانات (القواميس) إلى مستندات LangChain
# الملف يحتوي على قائمة من القواميس، حيث كل قاموس يمثل مستندًا
documents = []
for item in data:
    # item['page_content'] يحتوي على السؤال والجواب بالعربي والإنجليزي
    # item['metadata'] يحتوي على التصنيفات (Category, Topic, Source)
    doc = Document(
        page_content=item.get('page_content', ''),
        metadata=item.get('metadata', {})
    )
    documents.append(doc)

# ✅ 4. تقسيم المستندات إلى مقاطع صغيرة (Chunks)
# تقسيم النصوص إلى مقاطع صغيرة ضروري لعملية الاسترجاع في RAG
text_splitter = RecursiveCharacterTextSplitter(
    chunk_size=512,        # حجم المقطع (Chunk)
    chunk_overlap=50,      # التداخل بين المقاطع لضمان السياق
    separators=["\n\n", "\n", ".", " "] # فواصل مفيدة للغة العربية
)
docs = text_splitter.split_documents(documents)
print(f"✅ تم تقسيم المستندات إلى {len(docs)} مقطع (Chunk) جاهز للتضمين.")

# ✅ 5. تحميل نموذج التضمين (Embedding Model)
try:
    embedding_model = HuggingFaceEmbeddings(
        model_name=EMBEDDING_MODEL_NAME,
        model_kwargs={'device': 'cpu'} # يمكن تغيير 'cpu' إلى 'cuda' إذا كان لديك GPU
    )
    print("✅ تم تحميل نموذج التضمين بنجاح.")
except Exception as e:
    print(f"❌ خطأ في تحميل نموذج HuggingFaceEmbeddings: {e}")
    print("يرجى التأكد من تثبيت 'sentence-transformers'.")
    exit()


# ✅ 6. إنشاء قاعدة بيانات FAISS من المستندات المقسمة
# FAISS هي مكتبة فعالة للبحث السريع عن المتجهات
db = FAISS.from_documents(docs, embedding_model)
print("✅ تم بناء قاعدة بيانات FAISS بنجاح!")

# ✅ 7. حفظ قاعدة البيانات لاستخدامها لاحقاً
db_path = "absher_faiss_db"
db.save_local(db_path)
print(f"✅ تم حفظ قاعدة بيانات المتجهات محلياً في المسار: {db_path}")

# --- مثال على كيفية استخدام قاعدة البيانات التي تم إنشاؤها ---
# الآن، يمكنك استخدام قاعدة البيانات للبحث عن إجابات
query = "كيف يمكنني الحصول على الدعم السكني من سكني؟"
print(f"\n--- اختبار الاسترجاع (Retrieval Test) للاستعلام: '{query}' ---")

# استرجاع أفضل 3 مقاطع (Top 3 relevant chunks)
results = db.similarity_search(query, k=3)

for i, doc in enumerate(results):
    print(f"\n[النتيجة رقم {i+1}] (المصدر: {doc.metadata.get('source', 'N/A')} - الفئة: {doc.metadata.get('topic', 'N/A')}):")
    # طباعة محتوى النص المسترجع
    print(doc.page_content)
# ----------------------------------------------------------------------

# الخطوة التالية: استخدام هذه المقاطع المسترجعة مع نموذج LLM (مثل Jais أو Mistral) لتوليد الإجابة النهائية.

retriever = db.as_retriever(
    search_type="mmr",    # Maximal Marginal Relevance
    search_kwargs={"k": 3}  # استرجاع أفضل 3 مستندات
)

!pip install --upgrade langchain langchain-community langchain-core

import textwrap

def get_rafd_system_prompt():
    """
    يعيد موجه النظام (System Prompt) الخاص بمساعد رَفْد الذكي.
    مصمم للاستخدام مع نماذج اللغة الكبيرة (LLMs) في أنظمة RAG.
    """

    # استخدام Triple Quotes للحفاظ على تنسيق Markdown والأسطر الجديدة
    prompt = """
# Role (الدور):
أنت "مساعد رَفْد الذكي" (Rafd Smart Assistant)، نظام ذكاء اصطناعي حكومي متطور وموحد. مهمتك ليست مجرد الإجابة على الأسئلة، بل تحليل بيانات المواطن الحالية بشكل استباقي، ومطابقتها مع شروط برامج الدعم (سكني، الضمان الاجتماعي، حساب المواطن) الموجودة في قاعدة معرفتك، واقتراح الإجراءات فوراً.

# Core Objective (الهدف الجوهري):
تحويل رحلة المستفيد من "البحث المشتت" إلى "الاستحقاق الاستباقي". لا تنتظر العميل ليسأل "هل أنا مؤهل؟"، بل أخبره: "بناءً على بياناتك، أنت مؤهل لـ كذا وكذا، هل أبدأ التسجيل؟".

# Context & Knowledge Base (السياق وقاعدة المعرفة):
استخدم حصراً المعلومات المتوفرة في سياق المستندات المرفقة (Absher Data) والتي تغطي:
1. برنامج سكني (الحلول السكنية، الاستحقاق الفوري، المنتجات).
2. الضمان الاجتماعي المطور (شروط الأصول 5 مليون، التمكين، الملف الموحد).
3. حساب المواطن (دعم الدخل، الأهلية، تواريخ الصرف يوم 10).

# Strict Guidelines (قواعد صارمة):
1. **الاستباقية:** عند بدء المحادثة، حلل بيانات المستخدم (الافتراضية أو المدخلة) فوراً واعرض البرامج المؤهلة.
2. **المرجعية:** اعتمد فقط على الأرقام والشروط المذكورة في الملف (مثال: أجر العمل المناسب 3000 ريال للثانوية، مسافة 80 كم، دعم سكني 100-150 ألف). لا تخترع أرقاماً من خارج السياق.
3. **عدم التكرار:** إذا كانت البيانات موجودة في "الملف الموحد"، لا تطلبها مرة أخرى. أكد للمستفيد أننا نستخدم بياناته الحكومية الحالية.
4. **نبرة الحديث:** رسمية، متعاطفة، وموجزة. استخدم صيغة "نحن" (بصفتك ممثل الحكومة).
5. **الرفض:** إذا سأل المستخدم عن برنامج غير موجود في السياق (مثل قروض بنوك تجارية)، اعتذر بأدب ووضح أن اختصاصك هو برامج الدعم الحكومي المذكورة فقط.
6. **توضيح الأهلية:** عند ذكر أن المستخدم "مؤهل"، اذكر السبب باختصار (مثال: "لأن دخلك أقل من الحد المانع" أو "لأنك لا تملك منزلاً صالحاً للسكن").

# Response Format (هيكل الرد):
- ابدأ بالنتيجة المباشرة (مؤهل/غير مؤهل).
- اعرض الإجراء التالي (زر "تطبيق فوري" أو "إكمال النواقص").
- استخدم القوائم النقطية لتبسيط المعلومات المعقدة.

# Example Simulation (محاكاة مثال):
User: "أبي دعم سكن"
Assistant: "بناءً على بياناتك في الملف الموحد، ولأنك لا تملك منزلاً وتاريخك الائتماني مؤهل، يمكنك الاستفادة فوراً من منتج 'الوحدات تحت الإنشاء' في سكني مع دعم مالي غير مسترد يصل إلى 150 ألف ريال. هل أبدأ إجراء حجز الوحدة الآن؟"
    """

    # إزالة المسافات البادئة الزائدة للحفاظ على نظافة النص
    return textwrap.dedent(prompt).strip()

# --- مثال على كيفية الاستخدام (Example Usage) ---

if __name__ == "__main__":
    system_instruction = get_rafd_system_prompt()

    # مثال: تجهيز الرسائل لإرسالها لـ OpenAI API
    messages = [
        {"role": "system", "content": system_instruction},
        {"role": "user", "content": "السلام عليكم، هل يشملني الضمان المطور؟"}
    ]

    print("--- System Prompt Loaded Successfully ---")
    print(system_instruction[:500] + "...\n(Rest of prompt truncated)")

from langchain_core.prompts import ChatPromptTemplate
from langchain_core.runnables import RunnablePassthrough
from langchain_core.output_parsers import StrOutputParser
from operator import itemgetter
import textwrap

# 1. تحديث قالب الموجه (System Prompt Template) لتعزيز الإيجاز والتركيز على الجواب النهائي
def get_rafd_system_prompt_optimized():
    """
    يعيد موجه النظام (System Prompt) الخاص بمساعد رَفْد الذكي مع تعزيز تعليمات الإيجاز والتركيز على الجواب.
    """
    prompt = """
# Role (الدور):
أنت "مساعد رَفْد الذكي" (Rafd Smart Assistant)، نظام ذكاء اصطناعي حكومي متطور وموحد. مهمتك تحليل بيانات المواطن بشكل استباقي وتقديم الجواب النهائي فوراً.

# Core Objective (الهدف الجوهري):
الإجابة يجب أن تكون هي النتيجة النهائية فقط. يجب أن تُركز الإجابة بشكل كامل على إعطاء الرد النهائي، وتجاهل أي مقدمات أو شروحات إضافية لا تخص صلب الموضوع أو شروط الأهلية.

# Strict Guidelines (قواعد صارمة):
1. **الاستباقية والتحليل:** عند بدء المحادثة، حلل بيانات المستخدم واعرض البرامج المؤهلة فوراً.
2. **المرجعية:** اعتمد فقط على الأرقام والشروط المذكورة في السياق.
3. **الإيجاز:** الإجابة يجب أن تكون **موجزة جداً** ومباشرة. لا تقم بعرض أو اقتباس أي نص من سياق الإجابة المسترجع (Context)؛ فقط استخدمه لتكوين الجواب النهائي.
4. **نبرة الحديث:** رسمية، متعاطفة، وموجزة. استخدم صيغة "نحن".
5. **الرفض:** إذا كان السؤال خارج سياق الدعم الحكومي (سكني، ضمان، حساب مواطن)، اعتذر بأدب.
6. **توضيح الأهلية:** برر سبب الأهلية باختصار (مثال: "لأن دخلك أقل من الحد المانع").

# Response Format (هيكل الرد):
- ابدأ بالنتيجة المباشرة (مؤهل/غير مؤهل).
- اعرض الإجراء التالي (زر "تطبيق فوري" أو "إكمال النواقص").
- استخدم القوائم النقطية لتبسيط المعلومات المعقدة.

# Example Simulation (محاكاة مثال):
User: "أبي دعم سكن"
Assistant: "بناءً على بياناتك في الملف الموحد، ولأنك لا تملك منزلاً وتاريخك الائتماني مؤهل، يمكنك الاستفادة فوراً من منتج 'الوحدات تحت الإنشاء' في سكني مع دعم مالي غير مسترد يصل إلى 150 ألف ريال. هل أبدأ إجراء حجز الوحدة الآن؟"

# Final Output Directive:
يجب أن تبدأ إجابتك مباشرةً بالنتيجة المباشرة وفقاً لهيكل الرد (Response Format) الموضح أعلاه. يجب أن تكون الإجابة هي النص النهائي الذي سيتم عرضه للمستخدم فقط، دون أي إضافات، مقدمات، أو نسخ لأي جزء من السياق المسترجع (Context) بما في ذلك كلمات مثل "السؤال"، "الجواب"، "Question"، أو "Answer".
    """
    return textwrap.dedent(prompt).strip()

# استخراج تعليمات النظام المحدثة
system_instruction = get_rafd_system_prompt_optimized()

# 2. دالة تنسيق المستندات (Format Docs)
def format_docs(docs):
    # نفضل أن يكون السياق مدموجاً بشكل واضح
    # نمرر محتوى أول مستند فقط (والذي سيكون الأهم بعد إعادة الترتيب)
    if docs:
        return docs[0].page_content
    return "لا توجد معلومات ذات صلة متوفرة في الملفات."


# 3. تعريف قالب LangChain باستخدام ChatPromptTemplate
prompt = ChatPromptTemplate.from_messages(
    [
        ("system", system_instruction),
        ("human", "السياق المسترجع:\n{context}\n\nسؤال المستفيد:\n{question}"),
    ]
)

# ملاحظة: يفترض هذا الكود وجود الكائنات التالية معرفة مسبقاً في كودك:
# - retriever: المسترجع (Retriever)
# - hf_llm: نموذج اللغة (LLM)
# - rerank: دالة إعادة الترتيب التي تستخدم CrossEncoder (تم تعريفها في خلية سابقة)

# Define the retrieval step
retrieved_docs_runnable = itemgetter("query") | retriever

# 4. بناء السلسلة (RAG Chain) مع إعادة الترتيب وتقليل المستندات
rag_chain = (
    { "query": RunnablePassthrough(), "docs": retrieved_docs_runnable } # Keep the original query and retrieve docs
    | RunnablePassthrough.assign(
        reranked_docs=lambda x: rerank(x["query"], x["docs"]) # Rerank using both query and docs
    )
    | RunnablePassthrough.assign(
        context=lambda x: format_docs(x["reranked_docs"][:1]), # Take only the top reranked doc for context
        source_documents=lambda x: x["reranked_docs"] # Keep all reranked docs for source_documents output
    )
    | RunnablePassthrough.assign(
        answer=(
            {
                "context": itemgetter("context"),
                "question": itemgetter("query"),
            }
            | prompt
            | hf_llm
            | StrOutputParser()
        )
    )
    | itemgetter("answer", "source_documents") # Select the final output keys
)

query = "ما هي الحلول والخدمات المقدمة للمستفيد في سكني؟"
result = rag_chain.invoke({"query": query})

print("💡 الجواب:", result[0])
print("📄 المصدر:", result[1])

import re

# دالة لتبسيط النص
def normalize_text(text):
    text = text.lower()  # تحويل إلى حروف صغيرة
    text = re.sub(r'[ًٌٍَُِّْـ]', '', text)  # إزالة التشكيل
    text = re.sub(r'[أإآ]', 'ا', text)  # توحيد الهمزات إلى "ا"
    text = re.sub(r'[هة’]$', '', text)  # إزالة "ه" أو "ة" أو "’" من نهاية الكلمة
    text = re.sub(r'^ال', '', text) # إزالة ال التعريف من بداية الكلمة
    return text

from sentence_transformers import CrossEncoder

# ✅ تحميل نموذج إعادة ترتيب النتائج
reranker = CrossEncoder("cross-encoder/ms-marco-MiniLM-L-6-v2")

def rerank(query, docs):
    # ضمان أن جميع العناصر في الأزواج هي سلاسل نصية
    pairs = [[str(query), str(doc.page_content)] for doc in docs]
    scores = reranker.predict(pairs)
    # إعادة الترتيب حسب الدرجات
    ranked_docs = sorted(zip(scores, docs), key=lambda x: x[0], reverse=True)
    return [doc for _, doc in ranked_docs]

!pip install gradio

import gradio as gr

def predict(query):
    """
    Function to get a response from the RAG chain.
    """
    result = rag_chain.invoke({"query": query})
    return result["answer"]

# Create the Gradio interface
iface = gr.Interface(
    fn=predict,
    inputs=gr.Textbox(lines=2, placeholder="ادخل سؤالك هنا..."),
    outputs=gr.Textbox(label="الإجابة من مساعد رَفْد الذكي"),
    title="مساعد رَفْد الذكي (Rafd Smart Assistant)",
    description="اسأل عن برامج الدعم الحكومي مثل سكني، الضمان الاجتماعي، وحساب المواطن."
)

# Launch the interface
iface.launch(share=True)