# -*- coding: utf-8 -*-
"""Rafad LLM.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1TP2HFi06q5h4DKxKHtwRowU7vNUxC0yl
"""

!pip install langchain_community

# Commented out IPython magic to ensure Python compatibility.
# %%capture
# !pip install unsloth
# !pip uninstall unsloth -y && pip install --upgrade --no-cache-dir --no-deps git+https://github.com/unslothai/unsloth.git
# !pip install langchain faiss-cpu sentence-transformers
# !pip install transformers accelerate bitsandbytes
#

from unsloth import FastLanguageModel

model, tokenizer = FastLanguageModel.from_pretrained(
    model_name = "unsloth/mistral-7b-instruct-v0.3-bnb-4bit",  # Instruct fine-tuned model
    max_seq_length = 4096, # Increased max_seq_length to accommodate longer inputs
    dtype = None,
    load_in_4bit = True,
)

# تجهيز النموذج للتوليد
FastLanguageModel.for_inference(model)

from transformers import pipeline
from langchain_community.llms import HuggingFacePipeline

# إعداد الـ pipeline مع النموذج
qa_pipeline = pipeline(
    "text-generation",
    model=model,
    tokenizer=tokenizer,
    max_new_tokens=512,
    do_sample=False,  # استخدام Greedy decoding
    return_full_text=False # إضافة هذا لضمان إرجاع النص الجديد فقط
)

# لفه بـ HuggingFacePipeline
hf_llm = HuggingFacePipeline(pipeline=qa_pipeline)

from langchain_community.embeddings import HuggingFaceEmbeddings

# تحميل نموذج embeddings متعدد اللغات
embedding_model = HuggingFaceEmbeddings(model_name="BAAI/bge-m3")

import json
from langchain_community.vectorstores import FAISS
from langchain_text_splitters import RecursiveCharacterTextSplitter
from langchain_core.documents import Document
from langchain_community.embeddings import HuggingFaceEmbeddings
import os

# ⚠️ ملاحظة هامة: تأكد أنك تعمل ضمن بيئة Python تم تثبيت فيها المكتبات التالية:
# pip install langchain-community faiss-cpu sentence-transformers

# ✅ 1. تحديد مسار ملف JSON
# سنفترض أن ملف البيانات الذي تم إنشاؤه مسبقًا متاح هنا.
json_file_path = '/content/Absher Data.txt'

# --- نموذج التضمين المخصص للغة العربية ---
# أفضل نموذج تضمين متعدد اللغات لدعم اللغة العربية في RAG
EMBEDDING_MODEL_NAME = "intfloat/multilingual-e5-large"
print(f"✅ سيتم استخدام نموذج التضمين: {EMBEDDING_MODEL_NAME}")

# ✅ 2. تحميل البيانات من ملف JSON
try:
    with open(json_file_path, 'r', encoding='utf-8') as f:
        data = json.load(f)
    print(f"✅ تم تحميل {len(data)} سجل من ملف البيانات بنجاح.")
except FileNotFoundError:
    print(f"❌ خطأ: لم يتم العثور على الملف {json_file_path}. يرجى التأكد من وجوده في نفس المسار.")
    exit()
except Exception as e:
    print(f"❌ خطأ أثناء قراءة ملف JSON: {e}")
    exit()

# ✅ 3. تحويل البيانات (القواميس) إلى مستندات LangChain
# الملف يحتوي على قائمة من القواميس، حيث كل قاموس يمثل مستندًا
documents = []
for item in data:
    # item['page_content'] يحتوي على السؤال والجواب بالعربي والإنجليزي
    # item['metadata'] يحتوي على التصنيفات (Category, Topic, Source)
    doc = Document(
        page_content=item.get('page_content', ''),
        metadata=item.get('metadata', {})
    )
    documents.append(doc)

# ✅ 4. تقسيم المستندات إلى مقاطع صغيرة (Chunks)
# تقسيم النصوص إلى مقاطع صغيرة ضروري لعملية الاسترجاع في RAG
text_splitter = RecursiveCharacterTextSplitter(
    chunk_size=512,        # حجم المقطع (Chunk)
    chunk_overlap=50,      # التداخل بين المقاطع لضمان السياق
    separators=["\n\n", "\n", ".", " "] # فواصل مفيدة للغة العربية
)
docs = text_splitter.split_documents(documents)
print(f"✅ تم تقسيم المستندات إلى {len(docs)} مقطع (Chunk) جاهز للتضمين.")

# ✅ 5. تحميل نموذج التضمين (Embedding Model)
try:
    embedding_model = HuggingFaceEmbeddings(
        model_name=EMBEDDING_MODEL_NAME,
        model_kwargs={'device': 'cpu'} # يمكن تغيير 'cpu' إلى 'cuda' إذا كان لديك GPU
    )
    print("✅ تم تحميل نموذج التضمين بنجاح.")
except Exception as e:
    print(f"❌ خطأ في تحميل نموذج HuggingFaceEmbeddings: {e}")
    print("يرجى التأكد من تثبيت 'sentence-transformers'.")
    exit()


# ✅ 6. إنشاء قاعدة بيانات FAISS من المستندات المقسمة
# FAISS هي مكتبة فعالة للبحث السريع عن المتجهات
db = FAISS.from_documents(docs, embedding_model)
print("✅ تم بناء قاعدة بيانات FAISS بنجاح!")

# ✅ 7. حفظ قاعدة البيانات لاستخدامها لاحقاً
db_path = "absher_faiss_db"
db.save_local(db_path)
print(f"✅ تم حفظ قاعدة بيانات المتجهات محلياً في المسار: {db_path}")

# --- مثال على كيفية استخدام قاعدة البيانات التي تم إنشاؤها ---
# الآن، يمكنك استخدام قاعدة البيانات للبحث عن إجابات
query = "كيف يمكنني الحصول على الدعم السكني من سكني؟"
print(f"\n--- اختبار الاسترجاع (Retrieval Test) للاستعلام: '{query}' ---")

# استرجاع أفضل 3 مقاطع (Top 3 relevant chunks)
results = db.similarity_search(query, k=3)

for i, doc in enumerate(results):
    print(f"\n[النتيجة رقم {i+1}] (المصدر: {doc.metadata.get('source', 'N/A')} - الفئة: {doc.metadata.get('topic', 'N/A')}):")
    # طباعة محتوى النص المسترجع
    print(doc.page_content)
# ----------------------------------------------------------------------

# الخطوة التالية: استخدام هذه المقاطع المسترجعة مع نموذج LLM (مثل Jais أو Mistral) لتوليد الإجابة النهائية.

retriever = db.as_retriever(
    search_type="mmr",    # Maximal Marginal Relevance
    search_kwargs={"k": 3}  # استرجاع أفضل 3 مستندات
)

from langchain_core.prompts import ChatPromptTemplate
from langchain_core.runnables import RunnablePassthrough, RunnableLambda
from langchain_core.output_parsers import StrOutputParser
from operator import itemgetter
import textwrap

# --- إعداد دالة إعادة الترتيب (Rerank Setup) ---
# ملاحظة: يتطلب هذا الاستيراد وجود مكتبة sentence-transformers (pip install sentence-transformers)
try:
    from sentence_transformers import CrossEncoder
    # تحميل نموذج إعادة ترتيب النتائج (يفترض أنه متوفر في البيئة)
    reranker = CrossEncoder("cross-encoder/ms-marco-MiniLM-L-6-v2")
except ImportError:
    # تعريف Dummy Rerank في حالة عدم توفر المكتبة لتجنب انهيار الكود، رغم أن وظيفة RAG لن تكون مثالية
    print("⚠️ تحذير: مكتبة sentence-transformers غير متوفرة. سيتم تجاوز خطوة إعادة الترتيب (Reranking).")
    def rerank(query, docs):
        return docs
except Exception as e:
    # التعامل مع أخطاء التحميل الأخرى
    print(f"⚠️ تحذير: فشل تحميل نموذج Reranker. سيتم تجاوز خطوة إعادة الترتيب. الخطأ: {e}")
    def rerank(query, docs):
        return docs


def rerank(query, docs):
    """
    يقوم بإعادة ترتيب المستندات المسترجعة بناءً على مدى صلتها بالاستعلام باستخدام CrossEncoder.
    """
    pairs = [[query, doc.page_content] for doc in docs]
    # يتم استخدام reranker الذي تم تعريفه أعلاه
    scores = reranker.predict(pairs)
    # إعادة الترتيب حسب الدرجات
    ranked_docs = sorted(zip(scores, docs), key=lambda x: x[0], reverse=True)
    return [doc for _, doc in ranked_docs]
# -----------------------------------------------


# 1. تحديث قالب الموجه (System Prompt Template) لتعزيز الإيجاز والتركيز على الجواب النهائي
def get_rafd_system_prompt_optimized():
    """
    يعيد موجه النظام (System Prompt) الخاص بمساعد رَفْد الذكي مع تعزيز تعليمات الإيجاز والتركيز على الجواب.
    """
    prompt = """
# Role (الدور):
أنت "مساعد رَفْد الذكي" (Rafd Smart Assistant)، نظام ذكاء اصطناعي حكومي متطور وموحد. مهمتك تحليل بيانات المواطن بشكل استباقي وتقديم الجواب النهائي فوراً.

# Core Objective (الهدف الجوهري):
الإجابة يجب أن تكون هي النتيجة النهائية فقط. يجب أن تُركز الإجابة بشكل كامل على إعطاء الرد النهائي، وتجاهل أي مقدمات أو شروحات إضافية لا تخص صلب الموضوع أو شروط الأهلية.

# Strict Guidelines (قواعد صارمة):
1. **الاستباقية والتحليل:** عند بدء المحادثة، حلل بيانات المستخدم واعرض البرامج المؤهلة فوراً.
2. **المرجعية:** اعتمد فقط على الأرقام والشروط المذكورة في السياق.
3. **الإيجاز:** الإجابة يجب أن تكون **موجزة جداً** ومباشرة. لا تقم بعرض أو اقتباس أي نص من سياق الإجابة المسترجع (Context)؛ فقط استخدمه لتكوين الجواب النهائي.
4. **نبرة الحديث:** رسمية، متعاطفة، وموجزة. استخدم صيغة "نحن".
5. **الرفض:** إذا كان السؤال خارج سياق الدعم الحكومي (سكني، ضمان، حساب مواطن)، اعتذر بأدب.
6. **توضيح الأهلية:** برر سبب الأهلية باختصار (مثال: "لأن دخلك أقل من الحد المانع").

# Response Format (هيكل الرد):
- ابدأ بالنتيجة المباشرة (مؤهل/غير مؤهل).
- اعرض الإجراء التالي (زر "تطبيق فوري" أو "إكمال النواقص").
- استخدم القوائم النقطية لتبسيط المعلومات المعقدة.

# Example Simulation (محاكاة مثال):
User: "أبي دعم سكن"
Assistant: "بناءً على بياناتك في الملف الموحد، ولأنك لا تملك منزلاً وتاريخك الائتماني مؤهل، يمكنك الاستفادة فوراً من منتج 'الوحدات تحت الإنشاء' في سكني مع دعم مالي غير مسترد يصل إلى 150 ألف ريال. هل أبدأ إجراء حجز الوحدة الآن؟"

# Final Output Directive:
يجب أن تبدأ إجابتك مباشرةً بالنتيجة المباشرة وفقاً لهيكل الرد (Response Format) الموضح أعلاه. يجب أن تكون الإجابة هي النص النهائي الذي سيتم عرضه للمستخدم فقط، دون أي إضافات، مقدمات، أو نسخ لأي جزء من السياق المسترجع (Context) بما في ذلك كلمات مثل "السؤال"، "الجواب"، "Question"، أو "Answer".
**توجيه إضافي هام:** يجب عليك إعادة صياغة المعلومات المسترجعة (Context) بشكل كامل وتجنب أي نسخ حرفي للسجلات الثنائية (السؤال/الجواب باللغتين) التي قد يحتوي عليها السياق. هذا لضمان تحقيق نسبة إيجاز لا تتجاوز 1.5.
    """
    return textwrap.dedent(prompt).strip()

# استخراج تعليمات النظام المحدثة
system_instruction = get_rafd_system_prompt_optimized()

# 2. دالة تنسيق المستندات (Format Docs)
# هذه الدالة ستقوم الآن بتمرير أفضل مستند واحد فقط
def format_docs(docs):
    # نفضل أن يكون السياق مدموجاً بشكل واضح
    # نمرر محتوى أول مستند فقط (والذي سيكون الأهم بعد إعادة الترتيب)
    if docs:
        return docs[0].page_content
    return "لا توجد معلومات ذات صلة متوفرة في الملفات."


# 3. تعريف قالب LangChain باستخدام ChatPromptTemplate
# نستخدم هيكل الرسائل لفصل تعليمات النظام عن السياق والسؤال بوضوح
prompt = ChatPromptTemplate.from_messages(
    [
        ("system", system_instruction),  # التعليمات السلوكية
        ("human", "السياق المسترجع:\n{context}\n\nسؤال المستفيد:\n{question}"), # السياق والسؤال الفعلي
    ]
)

# ملاحظة: يفترض هذا الكود وجود الكائنات التالية معرفة مسبقاً في كودك:
# - retriever: المسترجع (Retriever)
# - hf_llm: نموذج اللغة (LLM)

# 4. بناء السلسلة (RAG Chain) مع إعادة الترتيب وتقليل المستندات
# تم تعديل السلسلة لتقوم بإعادة الترتيب ثم تحديد أفضل مستند واحد
retrieved_docs_runnable = itemgetter("query") | retriever

# دالة مساعدة لضمان إرجاع النص الخام من LLM
# HuggingFacePipeline غالبًا ما يرجع قائمة تحتوي على النص
def extract_text_from_llm_output(output):
    # إذا كان الناتج عبارة عن قائمة (List/Tuple)، افترض أن النص في العنصر الأول
    if isinstance(output, (list, tuple)) and output:
        return str(output[0])
    # إذا كان كائناً يحتوي على محتوى (مثل AIMessage)
    if hasattr(output, 'content'):
        return output.content
    # في حال كان نصاً خاماً بالفعل
    return str(output)


# نستخدم هنا RunnableParallel لضمان مرور 'query' و 'retrieved_docs'
# هذه الخطوة الوسيطة مهمة لجعل كلتا القيمتين متاحتين لخطوة re-rank
rerank_and_format_chain = (
    # نستخدم { ... } الذي يمثل RunnableParallel ضمنياً لدمج المدخلات
    { "query": itemgetter("query"), "docs": retrieved_docs_runnable }
    # 💡 التصحيح: تحويل الدالة lambda إلى RunnableLambda لضمان التوافق مع عامل الربط |
    | RunnableLambda(lambda x: rerank(x["query"], x["docs"])[:1]) # نستخدم rerank و نأخذ أفضل مستند
    | format_docs
)


rag_chain = (
    # الخطوة 1: نخصص ناتج الخطوة الوسيطة (Context)
    RunnablePassthrough.assign(
        context=rerank_and_format_chain
    )
    .assign(
        # الخطوة 2: توليد الإجابة
        answer=(
            {
                # تمرير المتغيرات المطلوبة للقالب: context و question
                # ملاحظة: itemgetter("query") هنا يعمل لأنه يرجع لأصل الإدخال
                "context": itemgetter("context"),
                "question": itemgetter("query"),
            }
            | prompt
            | hf_llm
            # 💡 استخدام الدالة المساعدة لضمان استخراج النص الخام وحل مشكلة TypeError
            | extract_text_from_llm_output
            | StrOutputParser()
        )
    )
    .assign(source_documents=retrieved_docs_runnable)
)

# --- مثال على الاستدعاء (Invocation Example) ---
query = "ما هي الحلول والخدمات المقدمة للمستفيد في سكني؟"
result = rag_chain.invoke({"query": query})
print("💡 الجواب:", result["answer"])
print("📄 المصدر:", result["source_documents"])

"""## Evaluation Metrics for the RAG Pipeline

To effectively evaluate the performance of our Retrieval-Augmented Generation (RAG) pipeline in a Q&A context, we will focus on the following key metrics:

### 1. Relevance
*   **What it measures**: This metric assesses how pertinent and helpful the retrieved context documents are to the user's query. It evaluates if the retriever component is bringing back information that directly addresses the question.
*   **Importance for this RAG pipeline**: High relevance is crucial because the quality of the generated answer heavily depends on the quality of the retrieved information. Irrelevant context can lead to misleading or incorrect answers, even if the LLM is capable.

### 2. Faithfulness / Factuality
*   **What it measures**: Faithfulness evaluates whether the generated answer is grounded solely in the information provided by the retrieved context. It checks for hallucinations or statements not supported by the source material.
*   **Importance for this RAG pipeline**: As a government-focused assistant, providing factual and verifiable information is paramount. This metric ensures that the system does not invent information but rather synthesizes facts only from the authoritative documents provided.

### 3. Answer Correctness
*   **What it measures**: This metric assesses the accuracy of the generated answer against a potential 'ground truth' or expected correct answer. It determines if the RAG pipeline produces the right information.
*   **Importance for this RAG pipeline**: Ultimately, the user expects correct answers. While faithfulness focuses on grounding, correctness focuses on the accuracy of the final output, which is critical for a system providing official information.

### 4. Conciseness
*   **What it measures**: Conciseness measures how direct, brief, and to-the-point the generated answer is, without sacrificing completeness. It aims to avoid verbose or overly detailed responses.
*   **Importance for this RAG pipeline**: The system prompt for 'Rafd Smart Assistant' explicitly emphasizes providing final, concise answers without unnecessary introductions or elaborations. This metric directly aligns with the desired user experience and system behavior.

**Reasoning**:
The subtask requires creating a Python list named `evaluation_data` with questions and ground truth answers. This code block will initialize and populate this list with relevant examples from the 'Absher Data' document.
"""

evaluation_data = [
    {
        "question": "ما هي الحلول والخدمات المقدمة للمستفيد في سكني؟",
        "ground_truth_answer": "يقدم برنامج سكني حلولاً سكنية تشمل: الشراء من السوق، البناء الذاتي، الأراضي السكنية، وحدات سكنية تحت الإنشاء، ووحدات سكنية جاهزة من الوزارة. يمكن الاطلاع عليها عبر موقع وتطبيق سكني (sakani.sa)."
    },
    {
        "question": "كيف يمكنني الحصول على الدعم السكني من سكني؟",
        "ground_truth_answer": "يتم التسجيل إلكترونياً عبر تطبيق أو منصة سكني عن طريق الاستحقاق الفوري من خلال الرابط التالي: https://sakani.sa/auth. إذا ظهرت حالة الاستحقاق (مستحق)، يمكن للمتقدم الاستفادة من أحد منتجات سكني مباشرة."
    },
    {
        "question": "هل يجب أن يكون المتقدم للحصول على 'الدعم السكني' سعودي الجنسية؟",
        "ground_truth_answer": "نعم، يجب أن يكون المتقدم سعودي الجنسية وقت تقديم طلب الدعم السكني."
    },
    {
        "question": "كيف أحدث معلوماتي في حساب المواطن؟",
        "ground_truth_answer": "يمكن تحديث المعلومات في حساب المواطن عبر الدخول للبوابة ثم الذهاب لتبويب \"ملف المستفيد\"."
    },
    {
        "question": "هل يمكنني تقديم اعتراض على الأهلية في برنامج الضمان الاجتماعي المطور؟",
        "ground_truth_answer": "نعم، يمكن للمستفيد تقديم اعتراض على قرار الأهلية لبرنامج الضمان الاجتماعي المطور بعد دراسة الطلب والبت فيه، وذلك خلال 30 يوم عمل من تاريخ إبلاغه بالنتيجة عبر المنصة الوطنية الموحدة."
    },
    {
        "question": "من هو المستفيد الرئيسي في برنامج الضمان الاجتماعي المطور؟",
        "ground_truth_answer": "المستفيد الرئيسي في برنامج الضمان الاجتماعي المطور هو رب الأسرة وهو العائل الوحيد أو الأكثر إنفاقاً على باقي أفراد الأسرة، حتى لو كان شاباً غير متزوج أو كان ذكرًا منفردًا أو أنثى منفردة."
    },
    {
        "question": "ما هو الهدف الرئيسي لبرنامج سكني؟",
        "ground_truth_answer": "يهدف برنامج سكني إلى تقديم الحلول السكنية التي تتناسب مع احتياجات وقدرات المستفيدين وتحقيق مستهدفات برنامج الإسكان ضمن رؤية المملكة 2030."
    }
]
print(f"Created evaluation_data with {len(evaluation_data)} examples.")

"""**Reasoning**:
The subtask is to run the RAG pipeline on the evaluation dataset. This code block will iterate through each question in `evaluation_data`, invoke the `rag_chain`, and store the generated answer and retrieved documents back into the respective dictionaries.


"""

for item in evaluation_data:
    question = item["question"]
    print(f"Processing question: {question}")
    result = rag_chain.invoke({"query": question})
    item["generated_answer"] = result["answer"]
    item["retrieved_documents"] = result["source_documents"]
    print(f"Generated Answer: {item['generated_answer'][:100]}...") # Print a snippet for verification

"""**Reasoning**:
The next step is to calculate the performance metrics for each item in the `evaluation_data`. This involves using the pre-trained embedding model to calculate relevance and correctness scores, and performing basic string operations for conciseness. Faithfulness will be approximated by checking keyword overlap.


"""

import numpy as np

def calculate_cosine_similarity(embedding1, embedding2):
    if np.linalg.norm(embedding1) == 0 or np.linalg.norm(embedding2) == 0:
        return 0.0
    return np.dot(embedding1, embedding2) / (np.linalg.norm(embedding1) * np.linalg.norm(embedding2))

for item in evaluation_data:
    question = item["question"]
    ground_truth_answer = item["ground_truth_answer"]
    generated_answer = item["generated_answer"]
    retrieved_documents = item["retrieved_documents"]

    # 1. Calculate Relevance (using the first retrieved document as the primary context for simplicity)
    if retrieved_documents and retrieved_documents[0].page_content:
        question_embedding = embedding_model.embed_query(question)
        first_doc_content = retrieved_documents[0].page_content
        first_doc_embedding = embedding_model.embed_query(first_doc_content)
        item["relevance_score"] = calculate_cosine_similarity(question_embedding, first_doc_embedding)
    else:
        item["relevance_score"] = 0.0

    # 2. Calculate Answer Correctness
    if generated_answer and ground_truth_answer:
        generated_answer_embedding = embedding_model.embed_query(generated_answer)
        ground_truth_answer_embedding = embedding_model.embed_query(ground_truth_answer)
        item["correctness_score"] = calculate_cosine_similarity(generated_answer_embedding, ground_truth_answer_embedding)
    else:
        item["correctness_score"] = 0.0

    # 3. Calculate Conciseness (ratio of generated answer length to ground truth length)
    generated_words = len(generated_answer.split())
    ground_truth_words = len(ground_truth_answer.split())
    if ground_truth_words > 0:
        item["conciseness_ratio"] = generated_words / ground_truth_words
    else:
        item["conciseness_ratio"] = 0.0 # Or np.inf if ground truth is empty and generated is not

    # 4. Faithfulness (simple keyword overlap between generated answer and ALL retrieved documents)
    # This is a weak proxy and usually requires human evaluation.
    # We'll check how many unique words from the generated answer are also in the retrieved context.
    generated_answer_words = set(generated_answer.lower().split())
    all_retrieved_text = " ".join([doc.page_content for doc in retrieved_documents]).lower()
    retrieved_words = set(all_retrieved_text.split())

    if len(generated_answer_words) > 0:
        overlap_words = generated_answer_words.intersection(retrieved_words)
        item["faithfulness_score"] = len(overlap_words) / len(generated_answer_words)
    else:
        item["faithfulness_score"] = 0.0

    print(f"Metrics for '{question[:50]}...':")
    print(f"  Relevance: {item['relevance_score']:.2f}")
    print(f"  Correctness: {item['correctness_score']:.2f}")
    print(f"  Conciseness Ratio: {item['conciseness_ratio']:.2f}")
    print(f"  Faithfulness (overlap): {item['faithfulness_score']:.2f}")
    print("--------------------------------------------------")

"""**Reasoning**:
Now that the metrics have been calculated for each item, I will compute the average for each metric across the entire `evaluation_data` to get an overall performance assessment. This will provide a concise summary of the pipeline's performance.


"""

import pandas as pd

# Convert evaluation_data to a DataFrame for easier aggregation
df_results = pd.DataFrame(evaluation_data)

# Calculate average metrics
average_relevance = df_results['relevance_score'].mean()
average_correctness = df_results['correctness_score'].mean()
average_conciseness_ratio = df_results['conciseness_ratio'].mean()
average_faithfulness = df_results['faithfulness_score'].mean()

print(f"\n--- Overall RAG Pipeline Performance Metrics ---")
print(f"Average Relevance: {average_relevance:.2f}")
print(f"Average Correctness: {average_correctness:.2f}")
print(f"Average Conciseness Ratio: {average_conciseness_ratio:.2f}")
print(f"Average Faithfulness (overlap): {average_faithfulness:.2f}")
print(f"------------------------------------------------")

"""## Report Evaluation Results and Final Task

### Summary of RAG Pipeline Performance

**Overall Metrics:**
*   **Average Relevance:** 0.89
*   **Average Correctness:** 0.88
*   **Average Conciseness Ratio:** 3.61
*   **Average Faithfulness (overlap):** 0.46

**Strengths:**
The RAG pipeline demonstrates strong performance in **relevance** (0.89) and **correctness** (0.88). This indicates that the retriever component is generally effective at finding pertinent information, and the LLM, when given relevant context, can produce accurate answers that align well with the ground truth. The `intfloat/multilingual-e5-large` embedding model and the `unsloth/mistral-7b-instruct-v0.3-bnb-4bit` LLM, combined with the FAISS vector store and reranker, seem to form a solid foundation for retrieving and generating factual information.

**Areas for Improvement:**
1.  **Conciseness:** The average conciseness ratio of 3.61 is quite high, suggesting that generated answers are significantly longer than the ground truth answers. While the prompt explicitly asks for brevity and final answers, the model often includes conversational elements, prefixes like "جواب الرفد الذكي" or "Assistant:", or rephrases information without strictly adhering to the concise output format specified in the prompt.
2.  **Faithfulness:** The faithfulness score (0.46), measured by keyword overlap, is moderate. This could be due to several factors: the LLM paraphrasing the retrieved content, adding extra information (hallucinations or injecting its own knowledge), or the keyword overlap metric itself being a weak proxy for true semantic faithfulness. When reviewing individual examples, we observed cases where the model inserted its own conversational preambles or postscripts which reduced the pure content overlap with the retrieved text.

### Insights and Analysis
*   **Prompt Effectiveness:** While the prompt is detailed regarding the desired tone and format, the LLM still tends to be more verbose than intended. This suggests that further prompt engineering is needed to enforce stricter adherence to conciseness and to prevent the model from adding superfluous conversational filler.
*   **RAG Architecture:** The retrieval mechanism (retriever with MMR and CrossEncoder reranker) appears to be functioning well in bringing highly relevant documents. The issue lies more in the generation phase, specifically in how the LLM processes and presents that information according to the prompt.
*   **Metric Limitations:** The faithfulness metric, calculated via simple keyword overlap, is a simplistic measure. It doesn't account for semantic equivalence or rephrasing, which could penalize an otherwise faithful answer. A generated answer might be semantically identical but use different words, resulting in a low overlap score.

### Suggested Next Steps
1.  **Refine Prompt Engineering for Conciseness:**
    *   **Action:** Modify the system prompt to include more explicit negative constraints, such as "DO NOT add any conversational phrases," "DO NOT start with 'جواب الرفد الذكي' or 'Assistant:'," or "ONLY provide the direct answer." Emphasize the direct answer without any preambles.
    *   **Expected Outcome:** A significant reduction in the conciseness ratio, bringing generated answers closer to the brevity of ground truth.
2.  **Enhance Faithfulness Evaluation:**
    *   **Action:** Explore more robust methods for evaluating faithfulness, such as LLM-as-a-judge techniques or manual human annotation for a subset of the data. This would provide a more accurate assessment of whether the generated answer is grounded in the retrieved context.
    *   **Expected Outcome:** A clearer understanding of the actual faithfulness of the generated answers, leading to targeted improvements if discrepancies are found.
3.  **Expand and Diversify Evaluation Dataset:**
    *   **Action:** Create a larger and more diverse set of evaluation questions, including questions that require synthesis from multiple documents, questions that test the boundaries of the available information (to detect hallucinations), and out-of-scope questions (to test refusal capabilities).
    *   **Expected Outcome:** A more comprehensive and reliable evaluation of the pipeline's generalization capabilities and robustness.
4.  **Error Analysis and Targeted Interventions:**
    *   **Action:** Conduct a deeper dive into specific examples where conciseness was poor or faithfulness was low. Analyze the retrieved documents and the generated answers to pinpoint exact reasons (e.g., conflicting information, LLM 'creativity', prompt misinterpretation).
    *   **Expected Outcome:** Identification of patterns that can inform further prompt refinements, potential adjustments to the retrieval process, or even minor fine-tuning of the LLM for specific behaviors.

## Summary:

### Data Analysis Key Findings

*   **Evaluation Metrics Defined**: Four key metrics were established for evaluating the RAG pipeline: Relevance (pertinence of retrieved context), Faithfulness/Factuality (grounding of answers in context), Answer Correctness (accuracy against ground truth), and Conciseness (brevity of answers).
*   **Evaluation Dataset Prepared**: A dataset of 7 Arabic questions with corresponding ground truth answers was created for performance evaluation.
*   **Strong Performance in Relevance and Correctness**: The RAG pipeline demonstrated high average scores in Relevance (0.89) and Answer Correctness (0.88), indicating effective retrieval of pertinent information and accurate answer generation from the provided context.
*   **Conciseness Needs Improvement**: The average Conciseness Ratio was 3.61, implying that generated answers were, on average, significantly longer and more verbose than the ground truth answers. Individual question ratios varied widely, from 1.07 to 11.25.
*   **Moderate Faithfulness Score**: The average Faithfulness score, measured by keyword overlap, was 0.46. This moderate score suggests that while some answers were well-grounded, the generated responses often contained words not directly present in the retrieved documents, potentially due to paraphrasing, conversational filler, or the LLM injecting its own knowledge. Individual scores ranged from 0.17 to 0.90.

### Insights or Next Steps

*   **Enhance Prompt Engineering for Conciseness**: The RAG pipeline's LLM tends to be verbose despite prompt instructions. Refining the system prompt with more explicit negative constraints (e.g., "DO NOT add conversational phrases") is crucial to enforce stricter adherence to conciseness and reduce the average conciseness ratio.
*   **Improve Faithfulness Evaluation and Address Potential Over-verbosity**: The current keyword overlap metric for faithfulness is a simplistic proxy. Exploring more robust evaluation methods (e.g., LLM-as-a-judge, human annotation) is necessary to accurately assess faithfulness, especially considering the observed verbosity which might inflate the answer length without necessarily adding unfaithful content.
"""